### ISSUE TITLE
Form HTML structure

### ISSUE THREAD

**Issue by al2bovek** [al2bovek/33-grupe-sign-up-p#7]
Form HTML structure

**Comment by NaincyKumariKnoldus** [comment]
Hello @al2bovek Can I do this please? Can you tell me what you want?

**Comment by al2bovek** [comment]
> Hello @al2bovek Can I do this please? Can you tell me what you want?

Hi. Thanks. I want to succeed in JS.

**Comment by al2bovek** [comment]
Ok
